// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: cardListMenu.proto

package pb

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Page  string `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardListMenu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_cardListMenu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_cardListMenu_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Page) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Page) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *Page) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type VCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNo     string `protobuf:"bytes,1,opt,name=cardNo,proto3" json:"cardNo,omitempty"`
	CardType   string `protobuf:"bytes,2,opt,name=cardType,proto3" json:"cardType,omitempty"`
	NameOnCard string `protobuf:"bytes,3,opt,name=nameOnCard,proto3" json:"nameOnCard,omitempty"`
	CifName    string `protobuf:"bytes,4,opt,name=cifName,proto3" json:"cifName,omitempty"`
	AccFlag    string `protobuf:"bytes,5,opt,name=accFlag,proto3" json:"accFlag,omitempty"`
	CardBranch string `protobuf:"bytes,6,opt,name=cardBranch,proto3" json:"cardBranch,omitempty"`
	InstantNon string `protobuf:"bytes,7,opt,name=instantNon,proto3" json:"instantNon,omitempty"`
}

func (x *VCard) Reset() {
	*x = VCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cardListMenu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VCard) ProtoMessage() {}

func (x *VCard) ProtoReflect() protoreflect.Message {
	mi := &file_cardListMenu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VCard.ProtoReflect.Descriptor instead.
func (*VCard) Descriptor() ([]byte, []int) {
	return file_cardListMenu_proto_rawDescGZIP(), []int{1}
}

func (x *VCard) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *VCard) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *VCard) GetNameOnCard() string {
	if x != nil {
		return x.NameOnCard
	}
	return ""
}

func (x *VCard) GetCifName() string {
	if x != nil {
		return x.CifName
	}
	return ""
}

func (x *VCard) GetAccFlag() string {
	if x != nil {
		return x.AccFlag
	}
	return ""
}

func (x *VCard) GetCardBranch() string {
	if x != nil {
		return x.CardBranch
	}
	return ""
}

func (x *VCard) GetInstantNon() string {
	if x != nil {
		return x.InstantNon
	}
	return ""
}

var File_cardListMenu_proto protoreflect.FileDescriptor

var file_cardListMenu_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5a, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x05, 0x56, 0x43,
	0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x4f,
	0x6e, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d,
	0x65, 0x4f, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x69, 0x66, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x69, 0x66, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x72, 0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x72, 0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x32, 0x32, 0x0a, 0x08, 0x63,
	0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x43, 0x61, 0x72, 0x64, 0x22, 0x00, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cardListMenu_proto_rawDescOnce sync.Once
	file_cardListMenu_proto_rawDescData = file_cardListMenu_proto_rawDesc
)

func file_cardListMenu_proto_rawDescGZIP() []byte {
	file_cardListMenu_proto_rawDescOnce.Do(func() {
		file_cardListMenu_proto_rawDescData = protoimpl.X.CompressGZIP(file_cardListMenu_proto_rawDescData)
	})
	return file_cardListMenu_proto_rawDescData
}

var file_cardListMenu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cardListMenu_proto_goTypes = []interface{}{
	(*Page)(nil),  // 0: service.Page
	(*VCard)(nil), // 1: service.VCard
}
var file_cardListMenu_proto_depIdxs = []int32{
	0, // 0: service.cardList.Get:input_type -> service.Page
	1, // 1: service.cardList.Get:output_type -> service.VCard
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cardListMenu_proto_init() }
func file_cardListMenu_proto_init() {
	if File_cardListMenu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cardListMenu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cardListMenu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cardListMenu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cardListMenu_proto_goTypes,
		DependencyIndexes: file_cardListMenu_proto_depIdxs,
		MessageInfos:      file_cardListMenu_proto_msgTypes,
	}.Build()
	File_cardListMenu_proto = out.File
	file_cardListMenu_proto_rawDesc = nil
	file_cardListMenu_proto_goTypes = nil
	file_cardListMenu_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CardListClient is the client API for CardList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardListClient interface {
	Get(ctx context.Context, in *Page, opts ...grpc.CallOption) (*VCard, error)
}

type cardListClient struct {
	cc grpc.ClientConnInterface
}

func NewCardListClient(cc grpc.ClientConnInterface) CardListClient {
	return &cardListClient{cc}
}

func (c *cardListClient) Get(ctx context.Context, in *Page, opts ...grpc.CallOption) (*VCard, error) {
	out := new(VCard)
	err := c.cc.Invoke(ctx, "/service.cardList/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardListServer is the server API for CardList service.
type CardListServer interface {
	Get(context.Context, *Page) (*VCard, error)
}

// UnimplementedCardListServer can be embedded to have forward compatible implementations.
type UnimplementedCardListServer struct {
}

func (*UnimplementedCardListServer) Get(context.Context, *Page) (*VCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterCardListServer(s *grpc.Server, srv CardListServer) {
	s.RegisterService(&_CardList_serviceDesc, srv)
}

func _CardList_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardListServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.cardList/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardListServer).Get(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.cardList",
	HandlerType: (*CardListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CardList_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cardListMenu.proto",
}
